package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// 1. SNOW_WHITE (雪白風格 - 預設)
val SnowWhiteBg = Color(0xFFFFFFFF)
val SnowWhiteSurface = Color(0xFFF8FAFC)
val SnowWhiteCardBg = Color(0xFFF1F5F9)
val SnowWhitePrimary = Color(0xFF2563EB)
val SnowWhiteOnPrimary = Color(0xFFFFFFFF)
val SnowWhitePrimaryContainer = Color(0xFFE0F2FE)
val SnowWhiteOnPrimaryContainer = Color(0xFF0369A1)
val SnowWhiteSecondary = Color(0xFF0EA5E9)
val SnowWhiteTertiary = Color(0xFF0D9488)
val SnowWhiteOnBg = Color(0xFF0F172A)

// 2. DARK (暗黑風格)
val DarkBg = Color(0xFF121218)
val DarkSurface = Color(0xFF1E1E28)
val DarkCardBg = Color(0xFF2B2B38)
val DarkPrimary = Color(0xFFD0BCFF)
val DarkOnPrimary = Color(0xFF381E72)
val DarkPrimaryContainer = Color(0xFF4F378B)
val DarkOnPrimaryContainer = Color(0xFFEADDFF)
val DarkSecondary = Color(0xFF38BDF8)
val DarkTertiary = Color(0xFFF472B6)
val DarkOnBg = Color(0xFFE6E0E9)

// 3. MECHANICAL (機械風格)
val MechBg = Color(0xFF18181B)
val MechSurface = Color(0xFF27272A)
val MechCardBg = Color(0xFF3F3F46)
val MechPrimary = Color(0xFFF59E0B)
val MechOnPrimary = Color(0xFF000000)
val MechPrimaryContainer = Color(0xFF78350F)
val MechOnPrimaryContainer = Color(0xFFFEF3C7)
val MechSecondary = Color(0xFF9CA3AF)
val MechTertiary = Color(0xFF06B6D4)
val MechOnBg = Color(0xFFF4F4F5)

// 4. CUTE (可愛風格)
val CuteBg = Color(0xFFFFF0F5)
val CuteSurface = Color(0xFFFFF5F8)
val CuteCardBg = Color(0xFFFCE7F3)
val CutePrimary = Color(0xFFEC4899)
val CuteOnPrimary = Color(0xFFFFFFFF)
val CutePrimaryContainer = Color(0xFFFBCFE8)
val CuteOnPrimaryContainer = Color(0xFF831843)
val CuteSecondary = Color(0xFFC084FC)
val CuteTertiary = Color(0xFFF43F5E)
val CuteOnBg = Color(0xFF4A0E2E)

// 5. SUNNY (陽光風格)
val SunnyBg = Color(0xFFFFFBEB)
val SunnySurface = Color(0xFFFEF3C7)
val SunnyCardBg = Color(0xFFFDE68A)
val SunnyPrimary = Color(0xFFD97706)
val SunnyOnPrimary = Color(0xFFFFFFFF)
val SunnyPrimaryContainer = Color(0xFFFEF08A)
val SunnyOnPrimaryContainer = Color(0xFF78350F)
val SunnySecondary = Color(0xFF0284C7)
val SunnyTertiary = Color(0xFF10B981)
val SunnyOnBg = Color(0xFF451A03)

// 6. CORPORATE (上班族風格)
val CorpBg = Color(0xFFF1F5F9)
val CorpSurface = Color(0xFFFFFFFF)
val CorpCardBg = Color(0xFFE2E8F0)
val CorpPrimary = Color(0xFF1E3A8A)
val CorpOnPrimary = Color(0xFFFFFFFF)
val CorpPrimaryContainer = Color(0xFFDBEAFE)
val CorpOnPrimaryContainer = Color(0xFF1E293B)
val CorpSecondary = Color(0xFF475569)
val CorpTertiary = Color(0xFF0EA5E9)
val CorpOnBg = Color(0xFF0F172A)

// 7. CASUAL (休閒風格)
val CasualBg = Color(0xFFF0FDF4)
val CasualSurface = Color(0xFFDCFCE7)
val CasualCardBg = Color(0xFFBBF7D0)
val CasualPrimary = Color(0xFF059669)
val CasualOnPrimary = Color(0xFFFFFFFF)
val CasualPrimaryContainer = Color(0xFFA7F3D0)
val CasualOnPrimaryContainer = Color(0xFF064E3B)
val CasualSecondary = Color(0xFFD97706)
val CasualTertiary = Color(0xFF0284C7)
val CasualOnBg = Color(0xFF062C19)
